<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;
use App\Models\Shop;

class SimpleHerbalProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get first category and shop, or use defaults
        $category = Category::first();
        $shop = Shop::first();
        
        if (!$category) {
            $category = Category::create([
                'title' => 'General Products',
                'active' => 'active',
                'show_on_home' => 'show',
            ]);
        }
        
        if (!$shop) {
            $shop = Shop::create([
                'name' => 'HerbnHouse Store',
                'slug' => 'herbnhouse-store',
                'description' => 'Premium herbal and natural products store',
                'is_active' => true,
                'admin_id' => 1,
                'commission_rate' => 10.00,
            ]);
        }

        $products = [
            // Hair Care Products
            [
                'title' => 'Natural Amla Powder for Hair Growth',
                'description' => 'Pure organic Amla powder rich in Vitamin C for healthy hair growth and shine.',
                'price' => 25.00,
                'selling_price' => 19.00,
                'quantity' => 100,
                'stock_status' => 'in_stock',
                'image' => 'products/amla-powder.jpg',
                'category_id' => $category->id,
                'shop_id' => $shop->id,
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'title' => 'Organic Shikakai Powder - Natural Hair Cleanser',
                'description' => 'Traditional Shikakai powder for natural hair cleansing and conditioning.',
                'price' => 22.00,
                'selling_price' => 18.00,
                'quantity' => 85,
                'stock_status' => 'in_stock',
                'image' => 'products/shikakai-powder.jpg',
                'category_id' => $category->id,
                'shop_id' => $shop->id,
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'title' => 'Herbal Hair Growth Oil Blend',
                'description' => 'Powerful blend of coconut, castor, and herbal oils for hair growth.',
                'price' => 35.00,
                'selling_price' => 28.00,
                'quantity' => 60,
                'stock_status' => 'in_stock',
                'image' => 'products/hair-oil.jpg',
                'category_id' => $category->id,
                'shop_id' => $shop->id,
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'title' => 'Coconut Oil - Cold Pressed Virgin',
                'description' => 'Pure virgin coconut oil for hair and skin care.',
                'price' => 30.00,
                'selling_price' => 25.00,
                'quantity' => 110,
                'stock_status' => 'in_stock',
                'image' => 'products/coconut-oil.jpg',
                'category_id' => $category->id,
                'shop_id' => $shop->id,
                'is_active' => true,
                'is_featured' => false,
            ],

            // Skin Care Products
            [
                'title' => 'Organic Turmeric Powder for Glowing Skin',
                'description' => 'Premium quality turmeric powder for natural skin glow and anti-inflammatory benefits.',
                'price' => 18.00,
                'selling_price' => 15.00,
                'quantity' => 120,
                'stock_status' => 'in_stock',
                'image' => 'products/turmeric-powder.jpg',
                'category_id' => $category->id,
                'shop_id' => $shop->id,
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'title' => 'Pure Neem Powder - Natural Skin Purifier',
                'description' => 'Natural neem powder with antibacterial properties for acne treatment.',
                'price' => 20.00,
                'selling_price' => 16.00,
                'quantity' => 95,
                'stock_status' => 'in_stock',
                'image' => 'products/neem-powder.jpg',
                'category_id' => $category->id,
                'shop_id' => $shop->id,
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'title' => 'Rose Water Toner - Natural & Pure',
                'description' => 'Pure rose water toner for hydrating and refreshing skin.',
                'price' => 15.00,
                'selling_price' => 12.00,
                'quantity' => 80,
                'stock_status' => 'in_stock',
                'image' => 'products/rose-water.jpg',
                'category_id' => $category->id,
                'shop_id' => $shop->id,
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'title' => 'Multani Mitti - Fuller\'s Earth Clay',
                'description' => 'Natural clay for deep cleansing and oil control.',
                'price' => 12.00,
                'selling_price' => 10.00,
                'quantity' => 150,
                'stock_status' => 'in_stock',
                'image' => 'products/multani-mitti.jpg',
                'category_id' => $category->id,
                'shop_id' => $shop->id,
                'is_active' => true,
                'is_featured' => false,
            ],

            // Ayurvedic Powders
            [
                'title' => 'Triphala Powder - Digestive Wellness',
                'description' => '100% natural Triphala powder for digestive health and detoxification.',
                'price' => 30.00,
                'selling_price' => 24.00,
                'quantity' => 70,
                'stock_status' => 'in_stock',
                'image' => 'products/triphala-powder.jpg',
                'category_id' => $category->id,
                'shop_id' => $shop->id,
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'title' => 'Ashwagandha Powder - Stress Relief',
                'description' => 'Premium Ashwagandha root powder for stress relief and energy boost.',
                'price' => 40.00,
                'selling_price' => 32.00,
                'quantity' => 55,
                'stock_status' => 'in_stock',
                'image' => 'products/ashwagandha-powder.jpg',
                'category_id' => $category->id,
                'shop_id' => $shop->id,
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'title' => 'Brahmi Powder - Memory Enhancer',
                'description' => 'Pure Brahmi powder for memory enhancement and mental clarity.',
                'price' => 35.00,
                'selling_price' => 28.00,
                'quantity' => 45,
                'stock_status' => 'in_stock',
                'image' => 'products/brahmi-powder.jpg',
                'category_id' => $category->id,
                'shop_id' => $shop->id,
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'title' => 'Moringa Powder - Superfood',
                'description' => 'Nutrient-rich Moringa leaf powder packed with vitamins and minerals.',
                'price' => 35.00,
                'selling_price' => 28.00,
                'quantity' => 70,
                'stock_status' => 'in_stock',
                'image' => 'products/moringa-powder.jpg',
                'category_id' => $category->id,
                'shop_id' => $shop->id,
                'is_active' => true,
                'is_featured' => false,
            ],

            // Essential Oils
            [
                'title' => 'Pure Lavender Essential Oil',
                'description' => 'Therapeutic grade lavender essential oil for relaxation and aromatherapy.',
                'price' => 45.00,
                'selling_price' => 38.00,
                'quantity' => 40,
                'stock_status' => 'in_stock',
                'image' => 'products/lavender-oil.jpg',
                'category_id' => $category->id,
                'shop_id' => $shop->id,
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'title' => 'Tea Tree Essential Oil - Antiseptic',
                'description' => 'Pure tea tree oil with natural antiseptic properties.',
                'price' => 35.00,
                'selling_price' => 29.00,
                'quantity' => 65,
                'stock_status' => 'in_stock',
                'image' => 'products/tea-tree-oil.jpg',
                'category_id' => $category->id,
                'shop_id' => $shop->id,
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'title' => 'Eucalyptus Essential Oil',
                'description' => 'Pure eucalyptus oil for respiratory health and aromatherapy.',
                'price' => 32.00,
                'selling_price' => 26.00,
                'quantity' => 50,
                'stock_status' => 'in_stock',
                'image' => 'products/eucalyptus-oil.jpg',
                'category_id' => $category->id,
                'shop_id' => $shop->id,
                'is_active' => true,
                'is_featured' => false,
            ],

            // Herbal Teas
            [
                'title' => 'Organic Green Tea - Antioxidant Rich',
                'description' => 'Premium organic green tea leaves rich in antioxidants.',
                'price' => 25.00,
                'selling_price' => 20.00,
                'quantity' => 90,
                'stock_status' => 'in_stock',
                'image' => 'products/green-tea.jpg',
                'category_id' => $category->id,
                'shop_id' => $shop->id,
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'title' => 'Chamomile Tea - Relaxation Blend',
                'description' => 'Soothing chamomile tea for relaxation and better sleep.',
                'price' => 22.00,
                'selling_price' => 18.00,
                'quantity' => 75,
                'stock_status' => 'in_stock',
                'image' => 'products/chamomile-tea.jpg',
                'category_id' => $category->id,
                'shop_id' => $shop->id,
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'title' => 'Ginger Lemon Tea - Immunity Booster',
                'description' => 'Warming ginger lemon tea blend for immunity and digestion.',
                'price' => 24.00,
                'selling_price' => 19.00,
                'quantity' => 85,
                'stock_status' => 'in_stock',
                'image' => 'products/ginger-lemon-tea.jpg',
                'category_id' => $category->id,
                'shop_id' => $shop->id,
                'is_active' => true,
                'is_featured' => false,
            ],

            // Immunity Boosters
            [
                'title' => 'Giloy Powder - Immunity Booster',
                'description' => 'Pure Giloy powder to boost immunity and fight infections naturally.',
                'price' => 28.00,
                'selling_price' => 23.00,
                'quantity' => 85,
                'stock_status' => 'in_stock',
                'image' => 'products/giloy-powder.jpg',
                'category_id' => $category->id,
                'shop_id' => $shop->id,
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'title' => 'Tulsi Powder - Holy Basil',
                'description' => 'Sacred Tulsi powder for immunity, respiratory health, and overall wellness.',
                'price' => 20.00,
                'selling_price' => 16.00,
                'quantity' => 100,
                'stock_status' => 'in_stock',
                'image' => 'products/tulsi-powder.jpg',
                'category_id' => $category->id,
                'shop_id' => $shop->id,
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'title' => 'Chyawanprash - Traditional Immunity Tonic',
                'description' => 'Traditional Ayurvedic immunity booster with 40+ herbs.',
                'price' => 45.00,
                'selling_price' => 38.00,
                'quantity' => 30,
                'stock_status' => 'in_stock',
                'image' => 'products/chyawanprash.jpg',
                'category_id' => $category->id,
                'shop_id' => $shop->id,
                'is_active' => true,
                'is_featured' => false,
            ],

            // Home Décor Products
            [
                'title' => 'Handcrafted Wooden Wall Hanging',
                'description' => 'Beautiful handcrafted wooden wall hanging for home decoration.',
                'price' => 85.00,
                'selling_price' => 68.00,
                'quantity' => 25,
                'stock_status' => 'in_stock',
                'image' => 'products/wooden-wall-hanging.jpg',
                'category_id' => $category->id,
                'shop_id' => $shop->id,
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'title' => 'Macrame Wall Hanging Shelf',
                'description' => 'Boho style macrame wall hanging shelf for plants and decorative items.',
                'price' => 65.00,
                'selling_price' => 52.00,
                'quantity' => 30,
                'stock_status' => 'in_stock',
                'image' => 'products/macrame-shelf.jpg',
                'category_id' => $category->id,
                'shop_id' => $shop->id,
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'title' => 'Buddha Palm Decorative Statue',
                'description' => 'Golden handcrafted Buddha palm statue for home decoration and positive energy.',
                'price' => 120.00,
                'selling_price' => 95.00,
                'quantity' => 15,
                'stock_status' => 'in_stock',
                'image' => 'products/buddha-palm.jpg',
                'category_id' => $category->id,
                'shop_id' => $shop->id,
                'is_active' => true,
                'is_featured' => true,
            ],
            [
                'title' => 'Natural Bamboo Wind Chimes',
                'description' => 'Handmade bamboo wind chimes for peaceful and harmonious ambiance.',
                'price' => 35.00,
                'selling_price' => 28.00,
                'quantity' => 40,
                'stock_status' => 'in_stock',
                'image' => 'products/bamboo-wind-chimes.jpg',
                'category_id' => $category->id,
                'shop_id' => $shop->id,
                'is_active' => true,
                'is_featured' => false,
            ],
            [
                'title' => 'Ceramic Incense Holder Set',
                'description' => 'Beautiful ceramic incense holder set with natural designs.',
                'price' => 25.00,
                'selling_price' => 20.00,
                'quantity' => 60,
                'stock_status' => 'in_stock',
                'image' => 'products/incense-holder.jpg',
                'category_id' => $category->id,
                'shop_id' => $shop->id,
                'is_active' => true,
                'is_featured' => false,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
