[package]
name = "laravel-app"
version = "0.1.0"

[command]
dockerfile = "Dockerfile"

[fs]
public = "public"

[env]
APP_ENV = "production"
APP_KEY = "base64:your_app_key_here"
DB_CONNECTION = "mysql"
DB_HOST = "your-db-host"
DB_PORT = "3306"
DB_DATABASE = "your-db-name"
DB_USERNAME = "your-db-user"
DB_PASSWORD = "your-db-password"
