[package]
name = "power-ranger"
version = "0.1.0"
description = "Laravel project on Wasmer"

[build]
steps = [
  "curl -sS https://getcomposer.org/installer | php",
  "php composer.phar install --optimize-autoloader --no-dev",
  "npm install",
  "npm run build"
]

[command]
name = "serve"
run = "php -S 0.0.0.0:8080 -t public"

[env]
APP_ENV = "production"
DB_CONNECTION = "mysql"
