[package]
name = "kshitijv17/power-ranger"
version = "0.1.0"
description = "Laravel project on Wasmer"



[build]
steps = [
  "curl -sS https://getcomposer.org/installer | php",
  "php composer.phar install --optimize-autoloader --no-dev",
  "npm install",
  "npm run build"
]

[command]
run = "php -S 0.0.0.0:8080 -t public"

[env]
APP_ENV = "production"
APP_KEY=base64:vxkAtQL0chIjtq4VCAKI5qQYGF6PUYDQ9WQmRjcyWKU=
DB_CONNECTION = "mysql"

