[package]
name = "kshitijv17/power-ranger"
version = "0.1.0"
description = "Laravel project on Wasmer"


[command]
run = "php -S 0.0.0.0:8000 -t public"

[build]
steps = [
  "composer install --optimize-autoloader --no-dev"
  "npm install",
  "npm run dev"
]


[env]
APP_ENV = "production"
APP_KEY=base64:vxkAtQL0chIjtq4VCAKI5qQYGF6PUYDQ9WQmRjcyWKU=
DB_CONNECTION = "mysql"

